### ISSUE TITLE
在1.20.50版本中不起作用

### ISSUE THREAD

**Issue by YueHua46** [mcbe-mods/Cut-tree-one-click#5]
这个插件在1.20.50版本中没有起作用

**Comment by lete114** [comment]
最近比较忙，没空更新

你可以试着修改 `/src/behavior_pack/manifest.json` 文件中，具体能不能用我不清楚。（如果新版本中没有对这个mod中使用的API进行调整，一下方式大概率是可行的）

```diff
{
  "dependencies": [
    {
      "module_name": "@minecraft/server",
-      "version": "1.7.0-beta"
+      "version": "1.8.0-beta"
    }
  ]
}
```

**Comment by YueHua46** [comment]
> 最近比较忙，没空更新
> 
> 你可以试着修改 `/src/behavior_pack/manifest.json` 文件中，具体能不能用我不清楚。（如果新版本中没有对这个mod中使用的API进行调整，一下方式大概率是可行的）
> 
> ```diff
> {
>   "dependencies": [
>     {
>       "module_name": "@minecraft/server",
> -      "version": "1.7.0-beta"
> +      "version": "1.8.0-beta"
>     }
>   ]
> }
> ```

我改了一下manifest.json为1.8.0，然后通过pnpm run builds跑了一遍后，重新导入pack，好像依然没有作用。
![image](https://github.com/mcbe-mods/Cut-tree-one-click/assets/83119504/ca9686a6-93db-4f98-9f1e-949003f209f6)
![image](https://github.com/mcbe-mods/Cut-tree-one-click/assets/83119504/67fe9fa7-70a8-4c30-bc82-1dda6c951a33)

**Comment by lete114** [comment]
可能官方对API进行了调整，你可以试试更新依赖 `pnpm add -D @minecraft/server@1.8.0-beta.1.20.50-stable`，然后看`src/behavior_pack/scripts/main.ts`有没有报错

**Comment by YueHua46** [comment]
> 可能官方对API进行了调整，你可以试试更新依赖 `pnpm add -D @minecraft/server@1.8.0-beta.1.20.50-stable`，然后看`src/behavior_pack/scripts/main.ts`有没有报错

![image](https://github.com/mcbe-mods/Cut-tree-one-click/assets/83119504/4c2c1d8c-07ad-4c7a-95ea-b1bdee0f8a56)
有报错，但我没咋接触过这个附加包的开发，我也不会改😂

**Comment by lete114** [comment]
就是一些ts的类型错误提示 `undefined`，无伤大雅

**Comment by lete114** [comment]
如果你不会改的话，你可以直接修改我打包好的包解压.mcaddon修改上面说的 `1.8.0-beta` 因该能正常运行

**Comment by YueHua46** [comment]
> 如果你不会改的话，你可以直接修改我打包好的包解压.mcaddon修改上面说的 `1.8.0-beta` 因该能正常运行

我已经将`package.json`中的版本按照你说的改为了`1.8.0-beta.1.20.50-stable`
![image](https://github.com/mcbe-mods/Cut-tree-one-click/assets/83119504/a859a391-8718-46f9-9356-32835cc0e33c)
然后运行了`pnpm run builds`，并且在`pack/minecraft.mcaddon`中修改了`manifest.json`中的`dependencies`版本如下
```json
  "dependencies": [
    {
      "module_name": "@minecraft/server",
      "version": "1.8.0-beta"
    }
  ]
```
但是在游戏当中还是没有作用

**Comment by lete114** [comment]
不用build了，你直接下载最新的 https://github.com/mcbe-mods/Cut-tree-one-click/releases `.mcaddon` 解压并修改里面的 `"version": "1.8.0-beta"` 然后再自己打包导入游戏就可以了

**Comment by YueHua46** [comment]
> 不用build了，你直接下载最新的 https://github.com/mcbe-mods/Cut-tree-one-click/releases `.mcaddon` 解压并修改里面的 `"version": "1.8.0-beta"` 然后再自己打包导入游戏就可以了

好的我稍等试一下，谢谢

**Comment by lete114** [comment]
已更新支持 1.20.5x 版本
