### ISSUE TITLE
Not Working In 1.20.51

### ISSUE THREAD

**Issue by RealRagnvald** [mcbe-mods/Cut-tree-one-click#6]
I downloaded the most recent release, which is the 1.0.7 version and added it to my realm and it is not chopping the trees down while using an axe and crouching.

**Comment by lete114** [comment]
Is your game version v1.20.5x? v1.0.7 only supports v1.20.5x

**Comment by lete114** [comment]
I just tested it and v1.0.7 is working fine in v1.20.5x

**Comment by RealRagnvald** [comment]
Yeah, I have version 1.20.51 on PlayStation. I had it placed at the top and it didn't work and moved it to the bottom and it still didn't work.

**Comment by RealRagnvald** [comment]
It seems to work on my realm world when I download the world to my device but not when it is on a realm.

**Comment by lete114** [comment]
I haven't tested version 1.20.51, thanks for the feedback, I'll make time to test it!

**Comment by RealRagnvald** [comment]
Appreciate it.

**Comment by lete114** [comment]
Version 1.20.51 doesn't have any major updates, it's working fine! (https://minecraft.wiki/w/Bedrock_Edition_1.20.51)
